# Generated by Django 5.2.13 on 2026-04-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runbook', '0002_schedulerheartbeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerheartbeat',
            name='sync_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
